//! Scale benchmark (WORK.org phase 7): programs generated from a mock
//! schema, planned by the command line with the mock linked in (the direct
//! backend), with the numbers that gate the phase.
//!
//!   cargo bench --bench scale                  # CI-sized: 10^3 resources
//!   cargo bench --bench scale -- --full        # 10^4 and 10^5 resources
//!   cargo bench --bench scale -- --resources 5000
//!   cargo bench --bench scale -- --process     # also plan with `dform` over gRPC
//!   cargo bench --bench scale -- --bin PATH    # ... with another build of it
//!   cargo bench --bench scale -- --out DIR     # keep the generated programs
//!
//! Each scale generates a schema of 10^3 types (`type_attr` rows: a fresh
//! `id` everywhere, an open `endpoint` on every tenth type), a program of N
//! resources (a `size`, a `parent` ref to an earlier resource's computed
//! id, and on one in a hundred a `format` over a ref to an open endpoint,
//! which is stuck), an edge relation over the first thousand resources with
//! its transitive closure (a recursive stratum), and a policy pack of 500
//! rules (tags, warnings over `attr`, denies over negation, counts).
//!
//! Reported per scale: partition-graph nodes, provenance bytes per fact,
//! stuck instances per null, the evaluator's read count (index lookups
//! plus tuples read: deterministic), and for the plan wall time and
//! instructions (`perf stat`, when perf is installed) with /proc/loadavg,
//! and the provider's share: the time spent in the mock's calls, which the
//! direct backend runs on the planning thread. The plan runs in a child
//! process (this bench, run again with `--plan-child DIR`) so perf counts
//! it alone.

use dform::plugin::Launch;
use dform::plugin::backend::{Call, CallError, Handler, Reply};
use dform::plugin::link::Link;
use dform::plugin::queue::{Order, Queue};
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Instant;

struct Scale {
    resources: usize,
    types: usize,
    rules: usize,
}

const TYPES: usize = 1000;
const RULES: usize = 500;
/// Resources that take part in the edge relation and its closure.
const EDGES: usize = 1000;

fn ty(t: usize) -> String {
    format!("gen.t{t:04}")
}

/// A type with an open computed `endpoint`.
fn has_endpoint(t: usize) -> bool {
    t.is_multiple_of(10)
}

fn schema(s: &Scale) -> String {
    let mut out = String::from("# Generated by benches/scale.rs.\n\n");
    for t in 0..s.types {
        let t = ty(t);
        writeln!(out, "type_provider({t}, \"fakecloud\")").unwrap();
        writeln!(
            out,
            "type_attr({t}, \"id\", \"string\", [\"computed\", \"id\"])"
        )
        .unwrap();
    }
    for t in (0..s.types).filter(|t| has_endpoint(*t)) {
        writeln!(
            out,
            "type_attr({}, \"endpoint\", \"string\", [\"computed\"])",
            ty(t)
        )
        .unwrap();
    }
    out
}

fn program(s: &Scale) -> String {
    let mut out =
        String::from("# Generated by benches/scale.rs.\n\nimport \"policy.df\"\n\nuse scale\n\n");
    for i in 0..s.resources {
        let t = i % s.types;
        write!(
            out,
            "resource {} r{i} {{\n  name = \"r{i}\"\n  size = {}\n",
            ty(t),
            i % 16
        )
        .unwrap();
        if i > 0 {
            let p = i / 4;
            writeln!(out, "  parent = r{p}.id").unwrap();
        }
        if i % 100 == 1 {
            // A format over an open endpoint: needs its content (Rule 2).
            let q = (i / 10) * 10;
            if has_endpoint(q % s.types) {
                writeln!(out, "  label = format(\"%s-x\", r{q}.endpoint)").unwrap();
            }
        }
        out.push_str("}\n");
    }
    out.push('\n');
    for i in 1..s.resources.min(EDGES) {
        writeln!(out, "edge(\"r{i}\", \"r{}\")", i / 4).unwrap();
    }
    out.push_str(
        "\nabove(a, b) where edge(a, b)\nabove(a, c) where above(a, b), edge(b, c)\ndepth(a, count(b)) where above(a, b)\n",
    );
    for n in 0..16 {
        writeln!(out, "size_ok({n})").unwrap();
    }
    out
}

fn policy(s: &Scale) -> String {
    let mut out = String::from("# Generated by benches/scale.rs.\n\npolicy scale {\n");
    for k in 0..s.rules {
        let t = ty(k % s.types);
        let rule = match k % 5 {
            0 => format!("set n.tags += {{ p{k}: \"on\" }} where n in {t}"),
            1 => format!("warn \"big {t}\" {{ r: n }} where {t}[n].size > 14"),
            2 => {
                format!("deny \"odd size on {t}\" {{ r: n }} where s = {t}[n].size, not size_ok(s)")
            }
            3 => format!("warn \"empty {t}\" {{ r: n }} where n in {t}, n.size == 0"),
            _ => format!("per_type(\"{t}\", count(n)) where n in {t}"),
        };
        writeln!(out, "  {rule}").unwrap();
    }
    out.push_str("}\n");
    out
}

fn generate(s: &Scale, dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("schema.df"), schema(s))?;
    std::fs::write(dir.join("main.df"), program(s))?;
    std::fs::write(dir.join("policy.df"), policy(s))?;
    let _ = std::fs::remove_dir_all(dir.join("dform.state"));
    Ok(())
}

fn loadavg() -> String {
    std::fs::read_to_string("/proc/loadavg")
        .map(|l| l.split_whitespace().take(3).collect::<Vec<_>>().join(" "))
        .unwrap_or_else(|_| "n/a".into())
}

const PLAN: [&str; 5] = ["dev", "--provider", "schema.df", "plan", "main.df"];

/// The mock, its calls timed.
struct Timed<H>(H);

/// Time spent in the provider's calls, in ns.
static IN_PROVIDER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);

impl<H: Handler> Handler for Timed<H> {
    fn handle(&self, call: Call) -> Result<Reply, CallError> {
        let start = Instant::now();
        let r = self.0.handle(call);
        IN_PROVIDER.fetch_add(
            start.elapsed().as_nanos() as u64,
            std::sync::atomic::Ordering::Relaxed,
        );
        r
    }
}

/// The direct backend, the mock's calls timed.
struct TimedDirect;

impl Launch for TimedDirect {
    fn mock(&self) -> anyhow::Result<Link> {
        let q = Queue::new(Timed(dform_mock::Mock::linked()), Order::Clock, false);
        Link::start("the mock (direct, timed)", Box::new(q))
    }

    fn plugin(&self, exe: &Path) -> anyhow::Result<Link> {
        anyhow::bail!("{}: the bench plans with the mock only", exe.display())
    }
}

/// `--plan-child DIR`: plan there with the direct backend, then say how
/// long the provider's calls took (on stderr: `provider-ns N`).
fn plan_child(dir: &Path) -> ! {
    std::env::set_current_dir(dir).expect("cd");
    let args = std::iter::once("dform").chain(PLAN).map(Into::into);
    let code = dform::cli::main(&TimedDirect, args);
    eprintln!(
        "provider-ns {}",
        IN_PROVIDER.load(std::sync::atomic::Ordering::Relaxed)
    );
    std::process::exit(if code == std::process::ExitCode::SUCCESS {
        0
    } else {
        1
    })
}

/// How a plan runs: this bench's child over the direct backend, or a
/// `dform` binary over gRPC.
enum How {
    Direct,
    Process(PathBuf),
}

struct Planned {
    wall: f64,
    instructions: Option<u64>,
    planned: bool,
    /// Seconds in the provider's calls (the direct backend).
    provider: Option<f64>,
}

/// A plan of the generated program: wall time, and instructions when
/// `perf` can count them (a process backend's provider process included).
fn plan(how: &How, dir: &Path) -> Planned {
    let perf = Command::new("perf").arg("--version").output().is_ok();
    let mut cmd = match how {
        How::Direct => {
            let mut c = Command::new(std::env::current_exe().expect("this bench"));
            // It runs in `dir` (below).
            c.args(["--plan-child", "."]);
            c
        }
        How::Process(bin) => {
            let mut c = Command::new(bin);
            c.args(PLAN);
            c
        }
    };
    let start = Instant::now();
    let out = if perf {
        Command::new("perf")
            .args(["stat", "-x,", "-e", "instructions:u", "--"])
            .arg(cmd.get_program())
            .args(cmd.get_args())
            .current_dir(dir)
            .output()
    } else {
        cmd.current_dir(dir).output()
    }
    .expect("run the plan");
    let wall = start.elapsed().as_secs_f64();
    let stderr = String::from_utf8_lossy(&out.stderr);
    let instructions = perf
        .then(|| {
            stderr
                .lines()
                .find(|l| l.contains("instructions"))
                .and_then(|l| l.split(',').next()?.parse().ok())
        })
        .flatten();
    let provider = stderr
        .lines()
        .find_map(|l| l.strip_prefix("provider-ns "))
        .and_then(|n| n.parse::<u64>().ok())
        .map(|ns| ns as f64 / 1e9);
    let planned = String::from_utf8_lossy(&out.stdout).contains("plan:");
    if !planned {
        let head: Vec<&str> = stderr.lines().take(5).collect();
        println!("  plan failed:\n    {}", head.join("\n    "));
    }
    Planned {
        wall,
        instructions,
        planned,
        provider,
    }
}

/// In-process: the partition graph, the provenance circuit and the stuck
/// instances of one evaluation.
fn inspect(dir: &Path) -> anyhow::Result<String> {
    let schema = dform::schema::load_provider(dir.join("schema.df").to_str().unwrap())?;
    let program = dform::loader::load_program(&[dir.join("main.df")])?;
    let program = dform::zset::with_policy_rules(program)?;
    let compiled = dform::partition::compile(&program, &schema.facts)?;
    let start = Instant::now();
    let (res, _) = dform::engine::eval(&program, &schema.facts)?;
    let eval = start.elapsed().as_secs_f64();
    let st = res.circuit.stats();
    let nulls: BTreeSet<&String> = res.stuck.iter().flat_map(|s| &s.nulls).collect();
    Ok(format!(
        "  partition nodes       {}\n  facts                 {}\n  provenance bytes/fact {:.0}\n  stuck instances       {} over {} nulls ({:.2} per null)\n  eval reads            {}\n  eval wall             {eval:.3}s",
        compiled.graph.nodes.len(),
        res.facts.len(),
        st.bytes as f64 / res.facts.len().max(1) as f64,
        res.stuck.len(),
        nulls.len(),
        res.stuck.len() as f64 / nulls.len().max(1) as f64,
        res.reads,
    ))
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if let [flag, dir] = args.as_slice()
        && flag == "--plan-child"
    {
        plan_child(Path::new(dir));
    }
    let mut hows = vec![("direct", How::Direct)];
    let mut bin: Option<PathBuf> = None;
    let mut out: Option<PathBuf> = None;
    let mut sizes = vec![1_000];
    let mut inspect_it = true;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--full" => sizes = vec![10_000, 100_000],
            "--resources" => {
                sizes = vec![
                    it.next()
                        .and_then(|n| n.parse().ok())
                        .expect("--resources N"),
                ]
            }
            "--process" => {
                bin.get_or_insert_with(|| PathBuf::from(env!("CARGO_BIN_EXE_dform")));
            }
            "--bin" => bin = Some(PathBuf::from(it.next().expect("--bin PATH"))),
            "--out" => out = Some(PathBuf::from(it.next().expect("--out DIR"))),
            "--no-inspect" => inspect_it = false,
            _ => {} // `cargo bench` passes --bench
        }
    }
    if let Some(bin) = bin {
        hows.push(("process", How::Process(bin)));
    }
    let keep = out.is_some();
    let root = out.unwrap_or_else(|| {
        std::env::temp_dir().join(format!("dform-scale-{}", std::process::id()))
    });
    for n in sizes {
        let s = Scale {
            resources: n,
            types: TYPES,
            rules: RULES,
        };
        let dir = root.join(format!("r{n}"));
        generate(&s, &dir).expect("generate");
        println!(
            "scale: {} resources, {} types, {} policy rules ({})",
            s.resources,
            s.types,
            s.rules,
            dir.display()
        );
        if inspect_it {
            match inspect(&dir) {
                Ok(r) => println!("{r}"),
                Err(e) => println!("  inspect failed: {e:#}"),
            }
        }
        for (name, how) in &hows {
            let before = loadavg();
            let p = plan(how, &dir);
            println!(
                "  plan ({name:7}) wall   {:.3}s{} (loadavg {before} -> {})",
                p.wall,
                if p.planned { "" } else { " (no plan printed)" },
                loadavg()
            );
            match p.instructions {
                Some(i) => println!("  plan ({name:7}) instr  {i}"),
                None => println!("  plan ({name:7}) instr  n/a (perf not available)"),
            }
            if let Some(t) = p.provider {
                println!(
                    "  plan ({name:7}) provider {t:.3}s ({:.1}% of the wall)",
                    100.0 * t / p.wall
                );
            }
        }
    }
    if !keep {
        let _ = std::fs::remove_dir_all(&root);
    }
}
