//! Scale benchmark (WORK.org phase 7): programs generated from a mock
//! schema, planned by the `dform` binary, with the numbers that gate the
//! phase.
//!
//!   cargo bench --bench scale                  # CI-sized: 10^3 resources
//!   cargo bench --bench scale -- --full        # 10^4 and 10^5 resources
//!   cargo bench --bench scale -- --resources 5000
//!   cargo bench --bench scale -- --bin PATH    # plan with another build
//!   cargo bench --bench scale -- --out DIR     # keep the generated programs
//!
//! Each scale generates a schema of 10^3 types (`type_attr` rows: a fresh
//! `id` everywhere, an open `endpoint` on every tenth type), a program of N
//! resources (a `size`, a `parent` ref to an earlier resource's computed
//! id, and on one in a hundred a `format` over a ref to an open endpoint,
//! which is stuck), an edge relation over the first thousand resources with
//! its transitive closure (a recursive stratum), and a policy pack of 500
//! rules (tags, warnings over `attr`, denies over negation, counts).
//!
//! Reported per scale: partition-graph nodes, provenance bytes per fact,
//! stuck instances per null, the evaluator's read count (index lookups
//! plus tuples read: deterministic), and for `dform plan` wall time and
//! instructions (`perf stat`, when perf is installed) with /proc/loadavg.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Instant;

struct Scale {
    resources: usize,
    types: usize,
    rules: usize,
}

const TYPES: usize = 1000;
const RULES: usize = 500;
/// Resources that take part in the edge relation and its closure.
const EDGES: usize = 1000;

fn ty(t: usize) -> String {
    format!("gen.t{t:04}")
}

/// A type with an open computed `endpoint`.
fn has_endpoint(t: usize) -> bool {
    t.is_multiple_of(10)
}

fn schema(s: &Scale) -> String {
    let mut out = String::from("# Generated by benches/scale.rs.\n\nedition 2026.\n\n");
    for t in 0..s.types {
        let t = ty(t);
        writeln!(out, "type_provider({t}, fakecloud).").unwrap();
        writeln!(out, "type_attr({t}, id, string, [computed, id]).").unwrap();
    }
    for t in (0..s.types).filter(|t| has_endpoint(*t)) {
        writeln!(out, "type_attr({}, endpoint, string, [computed]).", ty(t)).unwrap();
    }
    out
}

fn program(s: &Scale) -> String {
    let mut out = String::from(
        "# Generated by benches/scale.rs.\n\nedition 2026.\n\nimport \"policy.df\".\n\napply scale.\n\n",
    );
    for i in 0..s.resources {
        let t = i % s.types;
        write!(
            out,
            "resource {} r{i} {{\n  name = \"r{i}\"\n  size = {}\n",
            ty(t),
            i % 16
        )
        .unwrap();
        if i > 0 {
            let p = i / 4;
            writeln!(out, "  parent = ref({}, r{p}, .id)", ty(p % s.types)).unwrap();
        }
        if i % 100 == 1 {
            // A format over an open endpoint: needs its content (Rule 2).
            let q = (i / 10) * 10;
            if has_endpoint(q % s.types) {
                writeln!(
                    out,
                    "  label = format(\"%s-x\", ref({}, r{q}, .endpoint))",
                    ty(q % s.types)
                )
                .unwrap();
            }
        }
        out.push_str("}.\n");
    }
    out.push('\n');
    for i in 1..s.resources.min(EDGES) {
        writeln!(out, "edge(\"r{i}\", \"r{}\").", i / 4).unwrap();
    }
    out.push_str(
        "\nabove(A, B) :- edge(A, B).\n\
         above(A, C) :- above(A, B), edge(B, C).\n\
         depth(A, count(B)) :- above(A, B).\n",
    );
    for n in 0..16 {
        writeln!(out, "size_ok({n}).").unwrap();
    }
    out
}

fn policy(s: &Scale) -> String {
    let mut out = String::from(
        "# Generated by benches/scale.rs.\n\nedition 2026.\n\npolicy scale {\n  contributes arg to _ at .tags.\n",
    );
    for k in 0..s.rules {
        let t = ty(k % s.types);
        let rule = match k % 5 {
            0 => format!("arg_add({t}, N, .tags, {{ p{k}: on }}) :- want({t}, N)."),
            1 => format!("warn(\"big {t}\", {{ r: N }}) :- attr({t}, N, .size, S), S > 14."),
            2 => format!(
                "deny(\"odd size on {t}\", {{ r: N }}) :- attr({t}, N, .size, S), not size_ok(S)."
            ),
            3 => {
                format!("warn(\"empty {t}\", {{ r: N }}) :- want({t}, N), attr({t}, N, .size, 0).")
            }
            _ => format!("per_type(\"{t}\", count(N)) :- want({t}, N)."),
        };
        writeln!(out, "  {rule}").unwrap();
    }
    out.push_str("}.\n");
    out
}

fn generate(s: &Scale, dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(dir)?;
    std::fs::write(dir.join("schema.df"), schema(s))?;
    std::fs::write(dir.join("main.df"), program(s))?;
    std::fs::write(dir.join("policy.df"), policy(s))?;
    let _ = std::fs::remove_dir_all(dir.join(".dform"));
    Ok(())
}

fn loadavg() -> String {
    std::fs::read_to_string("/proc/loadavg")
        .map(|l| l.split_whitespace().take(3).collect::<Vec<_>>().join(" "))
        .unwrap_or_else(|_| "n/a".into())
}

/// `dform plan` over the generated program: wall time, and instructions
/// when `perf` can count them.
fn plan(bin: &Path, dir: &Path) -> (f64, Option<u64>, bool) {
    let args = ["--provider", "schema.df", "--file", "main.df", "plan"];
    let perf = Command::new("perf").arg("--version").output().is_ok();
    let start = Instant::now();
    let out = if perf {
        Command::new("perf")
            .args(["stat", "-x,", "-e", "instructions:u", "--"])
            .arg(bin)
            .args(args)
            .current_dir(dir)
            .output()
    } else {
        Command::new(bin).args(args).current_dir(dir).output()
    }
    .expect("run dform");
    let wall = start.elapsed().as_secs_f64();
    let stderr = String::from_utf8_lossy(&out.stderr);
    let instructions = perf
        .then(|| {
            stderr
                .lines()
                .find(|l| l.contains("instructions"))
                .and_then(|l| l.split(',').next()?.parse().ok())
        })
        .flatten();
    let planned = String::from_utf8_lossy(&out.stdout).contains("plan:");
    if !planned {
        let head: Vec<&str> = stderr.lines().take(5).collect();
        println!("  plan failed:\n    {}", head.join("\n    "));
    }
    (wall, instructions, planned)
}

/// In-process: the partition graph, the provenance circuit and the stuck
/// instances of one evaluation.
fn inspect(dir: &Path) -> anyhow::Result<String> {
    let schema = dform::schema::load_provider(dir.join("schema.df").to_str().unwrap())?;
    let program = dform::loader::load_program(&[dir.join("main.df")])?;
    let program = dform::zset::with_policy_rules(program)?;
    let compiled = dform::partition::compile(&program, &schema.facts)?;
    let start = Instant::now();
    let (res, _) = dform::engine::eval(&program, &schema.facts)?;
    let eval = start.elapsed().as_secs_f64();
    let st = res.circuit.stats();
    let nulls: BTreeSet<&String> = res.stuck.iter().flat_map(|s| &s.nulls).collect();
    Ok(format!(
        "  partition nodes       {}\n  facts                 {}\n  provenance bytes/fact {:.0}\n  stuck instances       {} over {} nulls ({:.2} per null)\n  eval reads            {}\n  eval wall             {eval:.3}s",
        compiled.graph.nodes.len(),
        res.facts.len(),
        st.bytes as f64 / res.facts.len().max(1) as f64,
        res.stuck.len(),
        nulls.len(),
        res.stuck.len() as f64 / nulls.len().max(1) as f64,
        res.reads,
    ))
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut bin = PathBuf::from(env!("CARGO_BIN_EXE_dform"));
    let mut out: Option<PathBuf> = None;
    let mut sizes = vec![1_000];
    let mut inspect_it = true;
    let mut it = args.iter();
    while let Some(a) = it.next() {
        match a.as_str() {
            "--full" => sizes = vec![10_000, 100_000],
            "--resources" => {
                sizes = vec![
                    it.next()
                        .and_then(|n| n.parse().ok())
                        .expect("--resources N"),
                ]
            }
            "--bin" => bin = PathBuf::from(it.next().expect("--bin PATH")),
            "--out" => out = Some(PathBuf::from(it.next().expect("--out DIR"))),
            "--no-inspect" => inspect_it = false,
            _ => {} // `cargo bench` passes --bench
        }
    }
    let keep = out.is_some();
    let root = out.unwrap_or_else(|| {
        std::env::temp_dir().join(format!("dform-scale-{}", std::process::id()))
    });
    for n in sizes {
        let s = Scale {
            resources: n,
            types: TYPES,
            rules: RULES,
        };
        let dir = root.join(format!("r{n}"));
        generate(&s, &dir).expect("generate");
        println!(
            "scale: {} resources, {} types, {} policy rules ({})",
            s.resources,
            s.types,
            s.rules,
            dir.display()
        );
        if inspect_it {
            match inspect(&dir) {
                Ok(r) => println!("{r}"),
                Err(e) => println!("  inspect failed: {e:#}"),
            }
        }
        let before = loadavg();
        let (wall, instructions, planned) = plan(&bin, &dir);
        println!(
            "  plan wall             {wall:.3}s{} (loadavg {before} -> {})",
            if planned { "" } else { " (no plan printed)" },
            loadavg()
        );
        match instructions {
            Some(i) => println!("  plan instructions     {i}"),
            None => println!("  plan instructions     n/a (perf not available)"),
        }
    }
    if !keep {
        let _ = std::fs::remove_dir_all(&root);
    }
}
